### ISSUE TITLE
JobPostings to Employment Agency

### ISSUE THREAD

**Issue by cryptogun** [kamranahmedse/design-patterns-for-humans#101]
Replacing `JobPostings` with `Employment Agency` would be more vivid I think.  
Maybe that's informer module not observer module.

**Comment by kamranahmedse** [comment]
Thanks

**Comment by ka3speed** [comment]
Gry h

**Comment by ka3speed** [comment]
Thanks

**Comment by cryptogun** [comment]
U R welcome!
