### ISSUE TITLE
Translation request

### ISSUE THREAD

**Issue by hachi8833** [kamranahmedse/design-patterns-for-humans#102]
We'd like to translate this into Japanese and publish on our tech blog https://techracho.bpsinc.jp/ if you're OK.

We make sure to do that based upon the MIT license. I just wonder how should we treat the logo and the title "Design Patterns for Humans" with trademark. 
I hope you permit us to do that. 

Best regards,

**Comment by kamranahmedse** [comment]
Go ahead. I am fine with it as long as you **clearly** put the attribution and link to the source.
