### ISSUE TITLE
Does someone make the java version? 

### ISSUE THREAD

**Issue by amikai** [kamranahmedse/design-patterns-for-humans#107]
Does someone make the java version? If not, I want to do this and PR recently. If somebody do this already, I will close the issue.

**Comment by Amorganskate** [comment]
These are design patterns these can be implemented in Java. There literally is no need to duplicate this in another language for a readme. Its fully readable.

**Comment by gokutek** [comment]
Aha, I made the C+++ version.

**Comment by kamranahmedse** [comment]
Hey @amikai, we have no plans of adding the language specific examples but thanks
