### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by vylenne** [kamranahmedse/design-patterns-for-humans#129]
Hello. I would like to translate your article into Russian. 
I hope you don't mind? The link to the original repository will be so that people can see that you are the creator.

**Comment by kambleaa007** [comment]
You can take it, and keep contributing

**Comment by vylenne** [comment]
OK, I'll fork your repo or add new branch. Anyway after new year holidays. Thank you.

**Comment by vylenne** [comment]
@kamranahmedse hello, I translated your article and created PR
