### ISSUE TITLE
Break down patterns into individual markdown files [Help offered]

### ISSUE THREAD

**Issue by sangupta** [kamranahmedse/design-patterns-for-humans#20]
Let the main README file contain hyperlinks to all patterns and share the overall intent. All patterns can be implemented in individual markdown files. This will ensure that pull-requests do not conflict and we know what changes went into each rather than scrolling long history.

I wish to offer help to split the file up.

**Comment by svenluijten** [comment]
-1 from me tbh, I agree with you in terms of organization, but from a user standpoint it'd be more annoying if you had to dig through several files to get to what you want. <kbd>CTRL+F</kbd> on the main README would be much quicker than to figure out what you're looking for and then click through.

**Comment by sangupta** [comment]
I would not agree with the thought - structured content has its own advantages than a single page. To have people use search, creating a custom GSE is an option.

**Comment by kamranahmedse** [comment]
@sangupta I think it is fine as a single page.
