### ISSUE TITLE
Factory Method / Builder examples

### ISSUE THREAD

**Issue by zejur** [kamranahmedse/design-patterns-for-humans#35]
Factory Method:

class HiringManager { <--- should be abstract

Builder: 

Incomplete example.
property $cheeze never used
class Burger doesn't exist

  public function build() : Burger { <---
        return $burger; <---
    }

**Comment by kamranahmedse** [comment]
For the property never used, it is fine as the example is just to give the idea. Rest of the stuff has been fixed. Thanks.
