### ISSUE TITLE
No information about design patterns for humans

### ISSUE THREAD

**Issue by punit-shah** [kamranahmedse/design-patterns-for-humans#45]
These are design patterns for making software, not humans as the name suggests.

**Comment by jrkeo** [comment]
Hi Dad, it's me, your cousin.

**Comment by kamranahmedse** [comment]
![image](https://cloud.githubusercontent.com/assets/4921183/23151333/6049c074-f813-11e6-959b-49d80848140b.png)

**Comment by elchamandemichaocan** [comment]
Entonces que agi

**Comment by remram44** [comment]
"for humans" is still a thing? As opposed to what? Are all the guides written up to this day not good enough "for humans" according to the author her?

Please stop calling things "for humans". It is ridiculous. Every programming lib/API is "for humans" to build upon. There are now [1,368 repositories called that way](https://github.com/search?q=%22for+humans%22) on GitHub, so you're not even setting yourself apart anymore. Please stop.

**Comment by remram44** [comment]
Also see [Charles Leifer's "For Humans" makes me cringe](http://charlesleifer.com/blog/describing-projects-as-for-humans-must-stop/) ([reddit](https://www.reddit.com/r/Python/comments/4a9sxa/describing_projects_as_for_humans_must_stop/))

**Comment by kamranahmedse** [comment]
@remram44 calm down :) 

It is just a metaphor and [doesn't matter](http://www.dummies.com/store/All-Titles.html) at all what you call it.

**Comment by Idnan** [comment]
@kamranahmedse 
![racism-even-aliens-are-against-to-it_o_2013191](https://cloud.githubusercontent.com/assets/6161794/23176737/d6af0d9a-f87d-11e6-94d0-e4073330d8be.jpg)

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
Not so strange if someone think the bar is hich set. But everybody aint on the same level.

**Comment by remram44** [comment]
@HansZwetslootAktionAktivAnarkist So those of us with engineering degrees aren't humans?

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
well. Your not aliens. human against outhers?

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Feb 21, 2017 at 6:41 PM +0100, "Remi Rampin" <notifications@github.com<mailto:notifications@github.com>> wrote:


@HansZwetslootAktionAktivAnarkist<https://github.com/HansZwetslootAktionAktivAnarkist> So those of us with engineering degrees aren't humans?

**Comment by peterlazar1993** [comment]
@remram44 Dude, chill. Wouldn't it be more productive to contribute to this repo with sample code in other languages.
@kamranahmedse Awesome stuff dude.

**Comment by DiglidiDudeNG** [comment]
I am 12 and what is this?

**Comment by manulaiko** [comment]
I agree, I read this guide because I needed help designing humans but all I found is software design.

**Comment by davidvb** [comment]
@manulaiko I'll have to report you to our grand overlord.. sorry about that. As you know designing humans has been prohibited exxons ago, due to the extreme destructive nature of these foul organisms.
The only pattern you needed to remember was "If human >94% = FuX0r3d

**Comment by mlnv** [comment]
@punit-shah Maybe my repo helps you https://github.com/mlnv/design-patterns-for-hoomans
