### ISSUE TITLE
Wrong instance name in Command pattern

### ISSUE THREAD

**Issue by janogarcia** [kamranahmedse/design-patterns-for-humans#51]
Thanks for putting this together, Kamran! 👏

I just spotted some inconsistencies in the invoker instance name.

```
$remote = new RemoteControl();
$remoteControl->submit($turnOn); // Bulb has been lit!
$remoteControl->submit($turnOff); // Darkness!
```

The name should be either `$remote` or `$remoteControl` everywhere.

**Comment by kamranahmedse** [comment]
Fixed. Thanks @janogarcia :-)
