### ISSUE TITLE
Have per language versions [ie:Python, Go]

### ISSUE THREAD

**Issue by 1fabunicorn** [kamranahmedse/design-patterns-for-humans#54]
As a somewhat beginner, having all the example code in Java is slightly overwhelming. I am quite comfortable in Python, so maybe we could convert some? Have a new development branch, with language specific parts. 

I'll help out to my ability in this front

**Comment by kamranahmedse** [comment]
@1fabunicorn thank you for opening the issue. There is already an issue for that https://github.com/kamranahmedse/design-patterns-for-humans/issues/10 and is in progress. Stay tuned.

**Comment by 1fabunicorn** [comment]
Thank you. Do you have plans to add branches for this?

**Comment by kamranahmedse** [comment]
Nope, there would be a website with the code examples in different languages
