### ISSUE TITLE
State Language Media in README

### ISSUE THREAD

**Issue by li-xinyang** [kamranahmedse/design-patterns-for-humans#56]
Don't you think it is better to state that you are using PHP as the media for all the samples?

**Comment by kamranahmedse** [comment]
Hi,
Thanks for reporting.
For branding it in PHP, I don't think so. Because the concepts are same; PHP is just for examples and examples in other languages is already underway. Currently, for examples, it is written before all of them.

**Comment by li-xinyang** [comment]
Not branding PHP but to let readers aware the context. I am reading the code sample and release it is written in PHP.

**Comment by kamranahmedse** [comment]
Done. Thanks.
