### ISSUE TITLE
Not an Issue - A suggestion for a youtube series

### ISSUE THREAD

**Issue by awingit** [kamranahmedse/design-patterns-for-humans#57]
As a developer who does not have qualifications or official training, I sometimes struggle grasping development concepts and methods. However, I am still able to build advanced web apps and even figure out how to get things done in various programming languages. When I started reading through this, I already had some questions and needed some clarity. Thats when I picture a video series being done to literally walk through each pattern and every piece of code being explained. So this is just a suggestion, if you see any value in it. I personally would love a video series to always refer to.

**Comment by li-xinyang** [comment]
That's gonna be time-consuming for both consumer and creator. I would suggest reading a book on DP is a better alternative.

**Comment by kamranahmedse** [comment]
I wish I had enough time for that but anyways thank you for suggestion though.
