### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by francischan714** [kamranahmedse/design-patterns-for-humans#58]
I'm ready for translating this repository in Chinese.

**Comment by li-xinyang** [comment]
There is another developer who is willing to do the same thing. @crane-yuan

https://github.com/kamranahmedse/design-patterns-for-humans/issues/10

**Comment by crane-yuan** [comment]
@francischan714 @li-xinyang 我们一同翻译吧，加我qq（1182248598）或者weixin（VioletLove2014）吧，商讨下任务分配吧！ :smile:

**Comment by li-xinyang** [comment]
I am currently busy on other projects but if you need a reviewer count me in. 👍  

我可以帮忙校对。

**Comment by kamranahmedse** [comment]
There is already an issue for that https://github.com/kamranahmedse/design-patterns-for-humans/issues/43. Closing.

**Comment by crane-yuan** [comment]
@li-xinyang Thanks.

**Comment by haiiiiiyun** [comment]
I didn't find a Chinese translation project around github, so I created one: https://github.com/haiiiiiyun/design-patterns-for-humans-cn.

The *Creational Design Patterns* part has already translated, and welcome to join.
