### ISSUE TITLE
Split into separate md files

### ISSUE THREAD

**Issue by bmeverett** [kamranahmedse/design-patterns-for-humans#60]
Having one `readme.md` is great but there is a lot of content here. Consider separating into multiple `.md` files to help break it up to avoid the endless scrolling.  As long as they have the `.md` extension Github will still display them just like a readme.

**Comment by UsulPro** [comment]
and it will be easier to make translations!

**Comment by bmeverett** [comment]
I created an example [here](https://github.com/bmeverett/design-patterns-for-humans/tree/separate-md). I can pull request this if you like it!

**Comment by bluej130** [comment]
This would be super helpful.

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
yeah l will read it and go to github and awnser as soon as can be..

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, Feb 22, 2017 at 3:27 PM +0100, "Brandon Everett" <notifications@github.com<mailto:notifications@github.com>> wrote:


I created an example here<https://github.com/bmeverett/design-patterns-for-humans/tree/separate-md>. I can pull request this if you like it!

**Comment by kamranahmedse** [comment]
Sort of duplicates https://github.com/kamranahmedse/design-patterns-for-humans/issues/10. Closing.
