### ISSUE TITLE
Make the snippets code following the PSR-2 Code Style Guide

### ISSUE THREAD

**Issue by luciano-jr** [kamranahmedse/design-patterns-for-humans#72]
I can do that little modification, just to incentive the adopt of PSR-2 for others developers.

**Comment by svenluijten** [comment]
Already discussed in #21, not accepted back then. Would still like to see this repo adopt a proper coding standard though.

**Comment by luciano-jr** [comment]
Well, I leave a comment in the issue #21 trying to explain my point. Thank you @svenluijten!
