### ISSUE TITLE
Female designers get less money (& no familiy name)?

### ISSUE THREAD

**Issue by rugk** [kamranahmedse/design-patterns-for-humans#83]
In the [composite part](https://github.com/kamranahmedse/design-patterns-for-humans#-composite):
```php
// Prepare the employees
$john = new Developer('John Doe', 12000);
$jane = new Designer('Jane', 10000);
```

So Jane has no surname and gets 2000 less than her colleague - okay he's a dev, but anyway…
At least the family name thing is irritating.

**Comment by mindctrl** [comment]
Not nearly as irritating as opening a non-issue that emails the 575 watching the repo.

**Comment by rugk** [comment]
Where 2 of 575 people used laugh or hooray Emojis. Also it's not a non-issue.

**Comment by DiglidiDudeNG** [comment]
Muh wage gap, wake up sheeple, this code snippet proves without a doubt that it's reaaaaal ! \*mouth-foam\*

**Comment by kamranahmedse** [comment]
Thanks @rugk for reporting. It was completely unintentional and in order to compensate that I have increased her salary to be 3000 more than her colleague.

Let me know if you find any other discrepancies; we wouldn't want to have any sad employees here ;)

**Comment by rugk** [comment]
Nice. :smile: 

She also got a last name. :+1: 
As I see they are probably sibling or so (at least the same family)… :smiley:

**Comment by septemberboy7** [comment]
Did you just assume Jane's gender?

**Comment by rugk** [comment]
@septemberboy7 What do you mean by that? I assume(d) Jane is a quite female name. Just thought so…
