### ISSUE TITLE
A missing array property found on a object

### ISSUE THREAD

**Issue by MahbbRah** [kamranahmedse/design-patterns-for-humans#89]
`class Developer implements Employee
{
    protected $salary;
    protected $name;
    public function __construct(string $name, float $salary)
    {
        $this->name = $name;
        $this->salary = $salary;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setSalary(float $salary)
    {
        $this->salary = $salary;
    }

    public function getSalary(): float
    {
        return $this->salary;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }
}`

On above codes from here `$this->roles` coming? I'm not getting this. is it coming from interfaces ?

**Comment by dkbnguyen** [comment]
It is missing. You would want to implement it. Take a look at [PR#88](https://github.com/kamranahmedse/design-patterns-for-humans/pull/88/commits/9584c0afbf34463288f4a72fd03d1da84795568a)
