### ISSUE TITLE
Observer error

### ISSUE THREAD

**Issue by cyberboyz** [kamranahmedse/design-patterns-for-humans#91]
When I type the code for the Observer one, I get this error : Fatal error: Interface 'Observer' not found in /opt/lampp/htdocs/designpattern/Behavioral/Observer.php on line 14.

Perhaps you could specify where can I find the code for interface Observer one or maybe type the implementation of the interface for Observer directly on your code. Thanks :).

**Comment by kamranahmedse** [comment]
Hey, the code in examples is not complete. I intentionally left the parts not relevant to the explanation to keep it concise.
