### ISSUE TITLE
Problem with the adapter example

### ISSUE THREAD

**Issue by peterfication** [kamranahmedse/design-patterns-for-humans#92]
https://github.com/kamranahmedse/design-patterns-for-humans#-adapter

Shouldn't it be

`And hunter expects any implementation of Lion interface to **roar**.`

And then in the code

```java
class Hunter
{
    public function hunt(Lion $lion)
    {
        $lion->roar();
    }
}
```

**Comment by WhiteMoll** [comment]
I think you are right. Without this call, the `Hunter` class seems useless.

**Comment by kamranahmedse** [comment]
Fixed. Thanks
