### ISSUE TITLE
Missing Specification Design Pattern

### ISSUE THREAD

**Issue by juuuuuu** [kamranahmedse/design-patterns-for-humans#95]
I think it's missing the `Specification` design pattern, from `Behavioral` category.  
See https://www.martinfowler.com/apsupp/spec.pdf for complete definition. I know it might be considered as an anti-pattern, what do you think about it?

**Comment by kamranahmedse** [comment]
Hey, the repository contains GOF Design Patterns, while Specification is an architectural pattern.
