### ISSUE TITLE
Adding Architectural patterns - Data Transfer Object Design Pattern

### ISSUE THREAD

**Issue by gopinath-langote** [kamranahmedse/design-patterns-for-humans#97]
1. Add a new type of pattern: `Architectural Patterns`.
2. Adding one example of this type i.e. `Data Transfer Object Design Pattern`.

**Comment by gopinath-langote** [comment]
@kamranahmedse Working on it!

**Comment by kamranahmedse** [comment]
Hi @gopinath-langote ,

Thank you for opening the issue but this guide is for `Design Patterns` only and is not meant for `Architectural patterns` and any PRs for it will not be accepted.

Thanks though.
